In [3]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.corpus import stopwords
import pandas as pd
import re

In [4]:
data = pd.read_csv("./tripadvisor_hotel_reviews.csv")

In [ ]:
data.info()

In [6]:
data.head()

                                              Review  Rating
0  nice hotel expensive parking got good deal sta...       4
1  ok nothing special charge diamond member hilto...       2
2  nice rooms not 4* experience hotel monaco seat...       3
3  unique, great stay, wonderful time hotel monac...       5
4  great stay great stay, went seahawk game aweso...       5

In [7]:
data.Review[0]

'nice hotel expensive parking got good deal stay hotel anniversary, arrived late evening took advice previous reviews did valet parking, check quick easy, little disappointed non-existent view room room clean nice size, bed comfortable woke stiff neck high pillows, not soundproof like heard music room night morning loud bangs doors opening closing hear people talking hallway, maybe just noisy neighbors, aveda bath products nice, did not goldfish stay nice touch taken advantage staying longer, location great walking distance shopping, overall nice experience having pay 40 parking night,  '

In [9]:
data['review_lowercase'] = data['Review'].str.lower()

In [11]:
data.head()

,Review,Rating,review_lowercase
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso..."

In [21]:
en_stopwords = stopwords.words('english')
en_stopwords.remove("not")

In [22]:
data['review_no_stopwords'] = data['review_lowercase']\
                                .apply(lambda x: ' '.join([word for word in x.split() \
                                                    if word not in(en_stopwords)]))

In [30]:
#data.head()
data['review_no_stopwords'][0]

'nice hotel expensive parking got good deal stay hotel anniversary, arrived late evening took advice previous reviews valet parking, check quick easy, little disappointed non-existent view room room clean nice size, bed comfortable woke stiff neck high pillows, not soundproof like heard music room night morning loud bangs doors opening closing hear people talking hallway, maybe noisy neighbors, aveda bath products nice, not goldfish stay nice touch taken advantage staying longer, location great walking distance shopping, overall nice experience pay 40 parking night,'

In [33]:
data['review_no_puncts'] = data.apply(lambda x: re.sub(r"[*]", r" star",x['review_no_stopwords']), axis=1)

In [35]:
#data.head()

In [38]:
data['review_no_puncts'] = data.apply(lambda x: re.sub(r"([^\w\s])", "", x['review_no_puncts']), axis=1)

In [41]:
#data['review_no_puncts'][0]

In [42]:
data['tokenize'] = data.apply(lambda x: word_tokenize(x['review_no_puncts']), axis=1)

In [43]:
data.head()

,Review,Rating,review_lowercase,review_no_stopwords,review_no_puncts,tokenize
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,"[nice, hotel, expensive, parking, got, good, d..."
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,"[ok, nothing, special, charge, diamond, member..."
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...,nice rooms not 4* experience hotel monaco seat...,nice rooms not 4 star experience hotel monaco ...,"[nice, rooms, not, 4, star, experience, hotel,..."
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac...",unique great stay wonderful time hotel monaco ...,"[unique, great, stay, wonderful, time, hotel, ..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso...",great stay great stay went seahawk game awesom...,"[great, stay, great, stay, went, seahawk, game..."

In [45]:
#data['tokenize'][0]

In [46]:
ps = PorterStemmer()

In [49]:
data["stemmed"] = data["tokenize"].apply(lambda x: [ps.stem(row) for row in x])

In [51]:
data['stemmed']

0      [nice, hotel, expens, park, got, good, deal, s...
1      [ok, noth, special, charg, diamond, member, hi...
2      [nice, room, not, 4, star, experi, hotel, mona...
3      [uniqu, great, stay, wonder, time, hotel, mona...
4      [great, stay, great, stay, went, seahawk, game...
                             ...
104    [fairmont, hotel, singapor, splendid, stay, fa...
105    [great, hotel, stay, hotel, night, rout, perth...
106    [great, hotel, centr, stay, 5, night, room, ov...
107    [great, locat, great, valu, great, hotel, husb...
108    [love, hotel, great, locat, stay, vacat, tour,...
Name: stemmed, Length: 109, dtype: object

In [52]:
lemma = WordNetLemmatizer()

In [53]:
data["lemma"]=data["tokenize"].apply(lambda x: [lemma.lemmatize(row) for row in x])
data["lemma"]

0      [nice, hotel, expensive, parking, got, good, d...
1      [ok, nothing, special, charge, diamond, member...
2      [nice, room, not, 4, star, experience, hotel, ...
3      [unique, great, stay, wonderful, time, hotel, ...
4      [great, stay, great, stay, went, seahawk, game...
                             ...
104    [fairmont, hotel, singapore, splendid, stayed,...
105    [great, hotel, stayed, hotel, night, route, pe...
106    [great, hotel, centre, stayed, 5, night, room,...
107    [great, location, great, value, great, hotel, ...
108    [lovely, hotel, great, location, stayed, vacat...
Name: lemma, Length: 109, dtype: object

In [54]:
clean_tokens = sum(data["lemma"],[])

In [62]:
unigrams = (pd.Series(nltk.ngrams(clean_tokens, 1)).value_counts())
print(unigrams)

(hotel,)         292
(room,)          275
(great,)         126
(not,)           122
(stay,)           95
                ...
(2005,)            1
(march,)           1
(unfriendly,)      1
(askew,)           1
(andstated,)       1
Name: count, Length: 2588, dtype: int64

In [65]:
bigrams = (pd.Series(nltk.ngrams(clean_tokens, 2)).value_counts())
print(bigrams)

(great, location)       24
(space, needle)         21
(hotel, monaco)         16
(great, hotel)          12
(pike, place)           12
                        ..
(control, bed)           1
(bed, breakast)          1
(breakast, included)     1
(included, deal)         1
(deal, class)            1
Name: count, Length: 8263, dtype: int64

In [67]:
n_grams = (pd.Series(nltk.ngrams(clean_tokens, 4)).value_counts())
print(n_grams)

(nonsmoking, room, king, bed)                  2
(nice, view, space, needle)                    2
(block, away, pike, place)                     2
(nice, hotel, husband, stayed)                 2
(space, needle, experience, music)             2
                                              ..
(unfortunately, warwick, seattle, hotel)       1
(warwick, seattle, hotel, dissapointment)      1
(seattle, hotel, dissapointment, trip)         1
(hotel, dissapointment, trip, 3)               1
(airconditionera, standard, arranged, stay)    1
Name: count, Length: 9389, dtype: int64